export const GET_USERDATA = "GET_USERDATA";

export const SET_CONTENT_COVER = "SET_CONTENT_COVER";
export const SET_CONTENT_SUMMARY = "SET_CONTENT_SUMMARY";
export const SET_ARR_SLIDE = "SET_ARR_SLIDE";
export const SET_TYPE_SLIDE = "SET_TYPE_SLIDE";
export const SET_ARR_SLIDE_CONTENT = "SET_ARR_SLIDE_CONTENT";
export const SET_KEY_SLIDE = "SET_KEY_SLIDE";
export const SET_BTN_SAVE = "SET_BTN_SAVE";
