import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Card from "../public/cardHover.png";
import Bg from "../public/gambaruhuyy.png";
import { DocumentAddIcon } from "@heroicons/react/solid";
import * as Containers from "../containers";
import {
  DotsVerticalIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
} from "@heroicons/react/solid";

const Gallery = () => {
  return (
    <Containers.Layout>
      <div className="w-full  container min-h-screen mb-6 " id="idx-gallery">
        <Head>
          <title>Gallery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* list template */}

        <div className="wrap-list-template block mt-5">
          <p className="text-black font-semibold mb-5">Last template</p>
          {/* list thumbnail */}
          <div className="flex flex-wrap gap-11">
            {[2, 2, 2, 2, 2, 2].map((item: any, idx: number) => (
              <div className="card" key={idx}>
                <Image src={Card} alt="" />
                <p className="text-content text-sm text-center">
                  Lorem, ipsum.
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="wrap-table-data mt-10">
          <p className="title-text mb-5 font-bold">Report</p>

          {/* table data */}

          <div className="wrap-form bg-white p-10 rounded-md shadow-md">
            <div className="wrap-search flex items-center justify-center">
              <Containers.Search />
            </div>

            <div className="wrap-table-data mt-10">
              <table className=" w-full">
                <thead className=" border-b text-left">
                  <tr>
                    <th className=" p-2">Client</th>
                    <th>Template Name</th>
                    <th>Type</th>
                    <th>Time</th>
                  </tr>
                </thead>
                {[2, 2, 2, 2, 2].map((item: any, idx: number) => (
                  <tbody key={idx}>
                    <tr className=" border-b">
                      <td className="p-2 w-2/4">
                        The Sliding Mr. Bones (Next Stop, Pottersville)
                      </td>
                      <td className="">
                        <div className="border-b p-2">asdads</div>
                        <div className="p-2">asdads</div>
                      </td>
                      <td className="">
                        <div className="border-b p-2">asdads</div>
                        <div className="p-2">asdads</div>
                      </td>
                      <td className="">
                        <div className="border-b p-2">asdads</div>
                        <div className="p-2">asdads</div>
                      </td>
                      <td className="">
                        <div className="border-b p-2">
                          <DotsVerticalIcon width={20} />
                        </div>
                        <div className="p-2">
                          <DotsVerticalIcon width={20} />
                        </div>
                      </td>
                    </tr>
                  </tbody>
                ))}
              </table>
            </div>

            {/* pagination======================== */}
            <div className="wrap-pagination gap-10 mt-10 flex items-center justify-end">
              <div className="row text-slate-400 flex items-center">
                Row per page : &nbsp;
                <select className="focus:outline-none cursor-pointer">
                  <option value="">8</option>
                  <option value="">9</option>
                  <option value="">10</option>
                </select>
              </div>
              <div className="pagination gap-4 flex items-center text-slate-400">
                <div>1-8 of 240</div>
                <div className="flex items-center gap-2">
                  <ChevronLeftIcon width={20} className=" cursor-pointer" />
                  <ChevronRightIcon width={20} className=" cursor-pointer" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Containers.Layout>
  );
};

export default Gallery;
